"""initial schema

Revision ID: bfb1660a6300
Revises: 
Create Date: 2026-06-16 14:21:37.990316
"""
from alembic import op
import sqlalchemy as sa


revision = 'bfb1660a6300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('lb_strategy', sa.String(length=30), nullable=False),
    sa.Column('fallback_aliases', sa.JSON(), nullable=False),
    sa.Column('cache_enabled', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_name'), ['name'], unique=True)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('default_base_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_name'), ['name'], unique=True)

    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('virtual_key_id', sa.Integer(), nullable=True),
    sa.Column('requested_model', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=True),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('provider_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_virtual_key_id'), ['virtual_key_id'], unique=False)

    op.create_table('virtual_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('allowed_aliases', sa.JSON(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('budget_period', sa.String(length=20), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('budget_anchor', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('virtual_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('org', sa.String(length=200), nullable=True),
    sa.Column('extra_headers', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_provider_id'), ['provider_id'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('upstream_model', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('pinned_params', sa.JSON(), nullable=False),
    sa.Column('default_params', sa.JSON(), nullable=False),
    sa.Column('drop_params', sa.JSON(), nullable=False),
    sa.Column('input_price', sa.Float(), nullable=False),
    sa.Column('output_price', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['aliases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_alias_id'), ['alias_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_credential_id'), ['credential_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_credential_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_alias_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_provider_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('virtual_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_keys_key_hash'))

    op.drop_table('virtual_keys')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_virtual_key_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_ts'))

    op.drop_table('request_logs')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_name'))

    op.drop_table('providers')
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_name'))

    op.drop_table('aliases')
    # ### end Alembic commands ###
